name: language_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/farmfresh logo.jpg
    - assets/customer to farmer 1.jpg
    - assets/fast delivery1.jpg
    - assets/pre order1.jpg
    - assets/pre order2.jpg
    - assets/smart farmer.jpg
