name: language_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  animated_text_kit: ^4.2.2
  table_calendar: ^3.1.2
  pie_chart: ^5.4.0
  flutter_translate: ^4.1.0
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/farmfresh logo.jpg
    - assets/customer to farmer 1.jpg
    - assets/fast delivery1.jpg
    - assets/pre order1.jpg
    - assets/pre order2.jpg
    - assets/smart farmer.jpg
    - assets/MyPhotoValid.jpg
    - assets/mangodemo.webp
    - assets/news.jpg

